"""Add connected field to vehicles

Revision ID: 4da4643cfa31
Revises: 791784f038cd
Create Date: 2024-09-22 12:57:06.382233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da4643cfa31'
down_revision: Union[str, None] = '791784f038cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'connected')
    # ### end Alembic commands ###
