"""Fix status field name

Revision ID: f53cac25a1de
Revises: 4da4643cfa31
Create Date: 2024-09-22 13:26:09.444538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53cac25a1de'
down_revision: Union[str, None] = '4da4643cfa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('vehicles', 'connected')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('connected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('vehicles', 'status')
    # ### end Alembic commands ###
