name: Deploy MSX API to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: | 
            ldamasio/msx-api:0.0.${{github.run_number}}
            ldamasio/msx-api:latest
