name: Deploy MSX API to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          context: ./
          file: ./docker/Dockerfile
      - name: Build the Docker image
        run: docker build -t ldamasio/msx-api:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Push the Docker image
        run: docker push ldamasio/msx-api:latest
